In [1]:
import pandas as pd

In [16]:
df = pd.read_csv("mabel.txt",header=None,on_bad_lines="skip",encoding='utf8')
df = df.drop(0)

In [21]:
df.columns=['Date','Chat']

In [22]:
df

        Date                                               Chat
1   05/12/19   1:42 pm - Mabel Infoziant: Hi this is Mabel w...
2   05/12/19   1:42 pm - Mabel Infoziant: What’s your full name
3   05/12/19                      1:42 pm - AR❤: Ramisha Rani K
4   05/12/19                      1:42 pm - Mabel Infoziant: Ok
5   05/12/19   1:42 pm - Mabel Infoziant: ramisharanik@gmail...
6   05/12/19          1:43 pm - Mabel Infoziant: Your email Id?
7   05/12/19                             1:43 pm - AR❤: Yes Mam
8   05/12/19   1:43 pm - Mabel Infoziant: I will send 2 abst...
9   05/12/19                            1:43 pm - AR❤: Yeah mam
10  05/12/19   1:43 pm - Mabel Infoziant: Give me the list t...
11  05/12/19   1:43 pm - Mabel Infoziant: Send me cbe office...
12  05/12/19   1:44 pm - AR❤: Yeah Mam within Evening I will...
13  05/12/19   1:45 pm - AR❤: Tomorrow I have to visit the o...
14  05/12/19                      1:48 pm - Mabel Infoziant: ok
15  05/12/19   1:48 pm - Mabel Infoziant: send the details o...
16  05/12/19   1:49 pm - AR❤: Sure mam. Soon I will share de...
17  05/12/19   2:00 pm - AR❤: I have read the Abstract mam. ...
18  05/12/19   2:04 pm - Mabel Infoziant: I think Vignesh ha...
19  05/12/19   2:04 pm - Mabel Infoziant: I have sent the ab...
20  05/12/19                              2:06 pm - AR❤: Ok mam
21  05/12/19   2:07 pm - AR❤: I have read both the abstract ...
22  05/12/19   4:44 pm - Mabel Infoziant: Yes we need to ya ...
23  05/12/19                           4:48 pm - AR❤: Sure mam.
24  05/12/19                   8:07 pm - AR❤: Shall I call mam?
25  08/12/19   10:45 pm - Mabel Infoziant: Hi I was at churc...
26  08/12/19                         11:52 pm - AR❤: It's k mam
27  08/12/19   11:55 pm - AR❤: Just to know the tomorrow pla...
28  09/12/19    12:09 pm - AR❤: Mam can u send Vignesh number??
29  09/12/19   12:13 pm - Mabel Infoziant: Vignesh ML Infozi...
30  09/12/19   12:23 pm - Mabel Infoziant: I was in a meetin...
31  09/12/19                    12:25 pm - AR❤: Can I cal u mam
32  09/12/19   12:26 pm - AR❤: Waiting for u r finalization ...
33  09/12/19   12:26 pm - AR❤: If we finiliaze I can work wi...
34  09/12/19   12:28 pm - AR❤: So what ever may be ..if you ...
35  09/12/19           12:28 pm - AR❤: You deleted this message
36  09/12/19                     12:29 pm - AR❤: Do the needful
37  09/12/19   12:41 pm - Mabel Infoziant: No ma please hold...
38  09/12/19                     12:42 pm - AR❤: Ok mam thank u
39  10/12/19   7:59 am - Mabel Infoziant: Ramisha we need to...
40  10/12/19   8:00 am - Mabel Infoziant: Be ready to discus...
41  10/12/19                            8:55 am - AR❤: Okay mam
42  12/12/19                      2:26 pm - Mabel Infoziant: ok
43  15/12/19                     8:22 pm - AR❤: Mam are u free?
44  15/12/19   8:40 pm - Mabel Infoziant: Am at church can c...
45  15/12/19   8:40 pm - AR❤: Kk mam. I will ask Arun brothe...
46  18/12/19                              3:09 pm - AR❤: Hi mam
47  18/12/19                    3:09 pm - AR❤: Any updates mam?
48  18/12/19   3:11 pm - Mabel Infoziant: U might have to st...
49  18/12/19   3:11 pm - Mabel Infoziant: There is one proje...
50  18/12/19                            3:12 pm - AR❤: Kk mam👍🏻

In [27]:
Message = df['Chat'].str.split('-',n=1,expand=True)

In [28]:
Message

             0                                                  1
1     1:42 pm     Mabel Infoziant: Hi this is Mabel we just spoke
2     1:42 pm              Mabel Infoziant: What’s your full name
3     1:42 pm                                 AR❤: Ramisha Rani K
4     1:42 pm                                 Mabel Infoziant: Ok
5     1:42 pm             Mabel Infoziant: ramisharanik@gmail.com
6     1:43 pm                     Mabel Infoziant: Your email Id?
7     1:43 pm                                        AR❤: Yes Mam
8     1:43 pm    Mabel Infoziant: I will send 2 abstracts for ...
9     1:43 pm                                       AR❤: Yeah mam
10    1:43 pm    Mabel Infoziant: Give me the list that u have...
11    1:43 pm    Mabel Infoziant: Send me cbe office address a...
12    1:44 pm    AR❤: Yeah Mam within Evening I will forward y...
13    1:45 pm    AR❤: Tomorrow I have to visit the office.yet ...
14    1:48 pm                                 Mabel Infoziant: ok
15    1:48 pm    Mabel Infoziant: send the details of office l...
16    1:49 pm    AR❤: Sure mam. Soon I will share details with...
17    2:00 pm    AR❤: I have read the Abstract mam. We can do ...
18    2:04 pm    Mabel Infoziant: I think Vignesh has the data...
19    2:04 pm          Mabel Infoziant: I have sent the abstracts
20    2:06 pm                                         AR❤: Ok mam
21    2:07 pm    AR❤: I have read both the abstract mam. We ca...
22    4:44 pm    Mabel Infoziant: Yes we need to ya about amou...
23    4:48 pm                                      AR❤: Sure mam.
24    8:07 pm                              AR❤: Shall I call mam?
25   10:45 pm    Mabel Infoziant: Hi I was at church couldn’t ...
26   11:52 pm                                     AR❤: It's k mam
27   11:55 pm    AR❤: Just to know the tomorrow plan mam.will ...
28   12:09 pm                AR❤: Mam can u send Vignesh number??
29   12:13 pm    Mabel Infoziant: Vignesh ML Infoziant.vcf (fi...
30   12:23 pm           Mabel Infoziant: I was in a meeting sorry
31   12:25 pm                                AR❤: Can I cal u mam
32   12:26 pm    AR❤: Waiting for u r finalization of rates fo...
33   12:26 pm    AR❤: If we finiliaze I can work with full inv...
34   12:28 pm    AR❤: So what ever may be ..if you think your ...
35   12:28 pm                       AR❤: You deleted this message
36   12:29 pm                                 AR❤: Do the needful
37   12:41 pm    Mabel Infoziant: No ma please hold I am in a ...
38   12:42 pm                                 AR❤: Ok mam thank u
39    7:59 am    Mabel Infoziant: Ramisha we need to talk toda...
40    8:00 am    Mabel Infoziant: Be ready to discuss about th...
41    8:55 am                                       AR❤: Okay mam
42    2:26 pm                                 Mabel Infoziant: ok
43    8:22 pm                                AR❤: Mam are u free?
44    8:40 pm    Mabel Infoziant: Am at church can call very l...
45    8:40 pm    AR❤: Kk mam. I will ask Arun brother. Small d...
46    3:09 pm                                         AR❤: Hi mam
47    3:09 pm                               AR❤: Any updates mam?
48    3:11 pm    Mabel Infoziant: U might have to start on the...
49    3:11 pm    Mabel Infoziant: There is one project that go...
50    3:12 pm                                       AR❤: Kk mam👍🏻

In [29]:
df["Time"] = Message[0]

In [30]:
df

        Date                                               Chat        Time
1   05/12/19   1:42 pm - Mabel Infoziant: Hi this is Mabel w...    1:42 pm
2   05/12/19   1:42 pm - Mabel Infoziant: What’s your full name    1:42 pm
3   05/12/19                      1:42 pm - AR❤: Ramisha Rani K    1:42 pm
4   05/12/19                      1:42 pm - Mabel Infoziant: Ok    1:42 pm
5   05/12/19   1:42 pm - Mabel Infoziant: ramisharanik@gmail...    1:42 pm
6   05/12/19          1:43 pm - Mabel Infoziant: Your email Id?    1:43 pm
7   05/12/19                             1:43 pm - AR❤: Yes Mam    1:43 pm
8   05/12/19   1:43 pm - Mabel Infoziant: I will send 2 abst...    1:43 pm
9   05/12/19                            1:43 pm - AR❤: Yeah mam    1:43 pm
10  05/12/19   1:43 pm - Mabel Infoziant: Give me the list t...    1:43 pm
11  05/12/19   1:43 pm - Mabel Infoziant: Send me cbe office...    1:43 pm
12  05/12/19   1:44 pm - AR❤: Yeah Mam within Evening I will...    1:44 pm
13  05/12/19   1:45 pm - AR❤: Tomorrow I have to visit the o...    1:45 pm
14  05/12/19                      1:48 pm - Mabel Infoziant: ok    1:48 pm
15  05/12/19   1:48 pm - Mabel Infoziant: send the details o...    1:48 pm
16  05/12/19   1:49 pm - AR❤: Sure mam. Soon I will share de...    1:49 pm
17  05/12/19   2:00 pm - AR❤: I have read the Abstract mam. ...    2:00 pm
18  05/12/19   2:04 pm - Mabel Infoziant: I think Vignesh ha...    2:04 pm
19  05/12/19   2:04 pm - Mabel Infoziant: I have sent the ab...    2:04 pm
20  05/12/19                              2:06 pm - AR❤: Ok mam    2:06 pm
21  05/12/19   2:07 pm - AR❤: I have read both the abstract ...    2:07 pm
22  05/12/19   4:44 pm - Mabel Infoziant: Yes we need to ya ...    4:44 pm
23  05/12/19                           4:48 pm - AR❤: Sure mam.    4:48 pm
24  05/12/19                   8:07 pm - AR❤: Shall I call mam?    8:07 pm
25  08/12/19   10:45 pm - Mabel Infoziant: Hi I was at churc...   10:45 pm
26  08/12/19                         11:52 pm - AR❤: It's k mam   11:52 pm
27  08/12/19   11:55 pm - AR❤: Just to know the tomorrow pla...   11:55 pm
28  09/12/19    12:09 pm - AR❤: Mam can u send Vignesh number??   12:09 pm
29  09/12/19   12:13 pm - Mabel Infoziant: Vignesh ML Infozi...   12:13 pm
30  09/12/19   12:23 pm - Mabel Infoziant: I was in a meetin...   12:23 pm
31  09/12/19                    12:25 pm - AR❤: Can I cal u mam   12:25 pm
32  09/12/19   12:26 pm - AR❤: Waiting for u r finalization ...   12:26 pm
33  09/12/19   12:26 pm - AR❤: If we finiliaze I can work wi...   12:26 pm
34  09/12/19   12:28 pm - AR❤: So what ever may be ..if you ...   12:28 pm
35  09/12/19           12:28 pm - AR❤: You deleted this message   12:28 pm
36  09/12/19                     12:29 pm - AR❤: Do the needful   12:29 pm
37  09/12/19   12:41 pm - Mabel Infoziant: No ma please hold...   12:41 pm
38  09/12/19                     12:42 pm - AR❤: Ok mam thank u   12:42 pm
39  10/12/19   7:59 am - Mabel Infoziant: Ramisha we need to...    7:59 am
40  10/12/19   8:00 am - Mabel Infoziant: Be ready to discus...    8:00 am
41  10/12/19                            8:55 am - AR❤: Okay mam    8:55 am
42  12/12/19                      2:26 pm - Mabel Infoziant: ok    2:26 pm
43  15/12/19                     8:22 pm - AR❤: Mam are u free?    8:22 pm
44  15/12/19   8:40 pm - Mabel Infoziant: Am at church can c...    8:40 pm
45  15/12/19   8:40 pm - AR❤: Kk mam. I will ask Arun brothe...    8:40 pm
46  18/12/19                              3:09 pm - AR❤: Hi mam    3:09 pm
47  18/12/19                    3:09 pm - AR❤: Any updates mam?    3:09 pm
48  18/12/19   3:11 pm - Mabel Infoziant: U might have to st...    3:11 pm
49  18/12/19   3:11 pm - Mabel Infoziant: There is one proje...    3:11 pm
50  18/12/19                            3:12 pm - AR❤: Kk mam👍🏻    3:12 pm

In [34]:
Message1 = Message[1].str.split(":",n=1,expand=True)

In [35]:
Message1

                   0                                                  1
1    Mabel Infoziant                     Hi this is Mabel we just spoke
2    Mabel Infoziant                              What’s your full name
3                AR❤                                     Ramisha Rani K
4    Mabel Infoziant                                                 Ok
5    Mabel Infoziant                             ramisharanik@gmail.com
6    Mabel Infoziant                                     Your email Id?
7                AR❤                                            Yes Mam
8    Mabel Infoziant     I will send 2 abstracts for u to start working
9                AR❤                                           Yeah mam
10   Mabel Infoziant                   Give me the list that u have too
11   Mabel Infoziant   Send me cbe office address and phone number I...
12               AR❤    Yeah Mam within Evening I will forward you mam.
13               AR❤   Tomorrow I have to visit the office.yet not I...
14   Mabel Infoziant                                                 ok
15   Mabel Infoziant   send the details of office location once u ge...
16               AR❤   Sure mam. Soon I will share details with you mam
17               AR❤   I have read the Abstract mam. We can do mam. ...
18   Mabel Infoziant   I think Vignesh has the data set will ask him...
19   Mabel Infoziant                          I have sent the abstracts
20               AR❤                                             Ok mam
21               AR❤   I have read both the abstract mam. We can do ...
22   Mabel Infoziant   Yes we need to ya about amount and all other ...
23               AR❤                                          Sure mam.
24               AR❤                                  Shall I call mam?
25   Mabel Infoziant         Hi I was at church couldn’t take your call
26               AR❤                                         It's k mam
27               AR❤   Just to know the tomorrow plan mam.will see t...
28               AR❤                    Mam can u send Vignesh number??
29   Mabel Infoziant           Vignesh ML Infoziant.vcf (file attached)
30   Mabel Infoziant                           I was in a meeting sorry
31               AR❤                                    Can I cal u mam
32               AR❤   Waiting for u r finalization of rates for our...
33               AR❤   If we finiliaze I can work with full involvem...
34               AR❤   So what ever may be ..if you think your are c...
35               AR❤                           You deleted this message
36               AR❤                                     Do the needful
37   Mabel Infoziant   No ma please hold I am in a hot meeting with ...
38               AR❤                                     Ok mam thank u
39   Mabel Infoziant   Ramisha we need to talk today i will call u a...
40   Mabel Infoziant     Be ready to discuss about the ML titles u have
41               AR❤                                           Okay mam
42   Mabel Infoziant                                                 ok
43               AR❤                                    Mam are u free?
44   Mabel Infoziant   Am at church can call very late or tomorrow only
45               AR❤   Kk mam. I will ask Arun brother. Small doubt ...
46               AR❤                                             Hi mam
47               AR❤                                   Any updates mam?
48   Mabel Infoziant     U might have to start on the WhatsApp analysis
49   Mabel Infoziant            There is one project that got committed
50               AR❤                                           Kk mam👍🏻

In [36]:
df["Name"] = Message1[0]

In [38]:
df["Chat"] = Message[1]

In [40]:
df = df[["Date","Time","Name","Chat"]]

In [41]:
df

,Date,Time,Name,Chat
1,05/12/19,1:42 pm,Mabel Infoziant,Mabel Infoziant: Hi this is Mabel we just spoke
2,05/12/19,1:42 pm,Mabel Infoziant,Mabel Infoziant: What’s your full name
3,05/12/19,1:42 pm,AR❤,AR❤: Ramisha Rani K
4,05/12/19,1:42 pm,Mabel Infoziant,Mabel Infoziant: Ok
5,05/12/19,1:42 pm,Mabel Infoziant,Mabel Infoziant: ramisharanik@gmail.com
6,05/12/19,1:43 pm,Mabel Infoziant,Mabel Infoziant: Your email Id?
7,05/12/19,1:43 pm,AR❤,AR❤: Yes Mam
8,05/12/19,1:43 pm,Mabel Infoziant,Mabel Infoziant: I will send 2 abstracts for ...
9,05/12/19,1:43 pm,AR❤,AR❤: Yeah mam
10,05/12/19,1:43 pm,Mabel Infoziant,Mabel Infoziant: Give me the list that u have...
11,05/12/19,1:43 pm,Mabel Infoziant,Mabel Infoziant: Send me cbe office address a...
12,05/12/19,1:44 pm,AR❤,AR❤: Yeah Mam within Evening I will forward y...
13,05/12/19,1:45 pm,AR❤,AR❤: Tomorrow I have to visit the office.yet ...
14,05/12/19,1:48 pm,Mabel Infoziant,Mabel Infoziant: ok
15,05/12/19,1:48 pm,Mabel Infoziant,Mabel Infoziant: send the details of office l...
16,05/12/19,1:49 pm,AR❤,AR❤: Sure mam. Soon I will share details with...
17,05/12/19,2:00 pm,AR❤,AR❤: I have read the Abstract mam. We can do ...
18,05/12/19,2:04 pm,Mabel Infoziant,Mabel Infoziant: I think Vignesh has the data...
19,05/12/19,2:04 pm,Mabel Infoziant,Mabel Infoziant: I have sent the abstracts
20,05/12/19,2:06 pm,AR❤,AR❤: Ok mam
21,05/12/19,2:07 pm,AR❤,AR❤: I have read both the abstract mam. We ca...
22,05/12/19,4:44 pm,Mabel Infoziant,Mabel Infoziant: Yes we need to ya about amou...
23,05/12/19,4:48 pm,AR❤,AR❤: Sure mam.
24,05/12/19,8:07 pm,AR❤,AR❤: Shall I call mam?
25,08/12/19,10:45 pm,Mabel Infoziant,Mabel Infoziant: Hi I was at church couldn’t ...
26,08/12/19,11:52 pm,AR❤,AR❤: It's k mam
27,08/12/19,11:55 pm,AR❤,AR❤: Just to know the tomorrow plan mam.will ...
28,09/12/19,12:09 pm,AR❤,AR❤: Mam can u send Vignesh number??
29,09/12/19,12:13 pm,Mabel Infoziant,Mabel Infoziant: Vignesh ML Infoziant.vcf (fi...
30,09/12/19,12:23 pm,Mabel Infoziant,Mabel Infoziant: I was in a meeting sorry
31,09/12/19,12:25 pm,AR❤,AR❤: Can I cal u mam
32,09/12/19,12:26 pm,AR❤,AR❤: Waiting for u r finalization of rates fo...
33,09/12/19,12:26 pm,AR❤,AR❤: If we finiliaze I can work with full inv...
34,09/12/19,12:28 pm,AR❤,AR❤: So what ever may be ..if you think your ...
35,09/12/19,12:28 pm,AR❤,AR❤: You deleted this message
36,09/12/19,12:29 pm,AR❤,AR❤: Do the needful
37,09/12/19,12:41 pm,Mabel Infoziant,Mabel Infoziant: No ma please hold I am in a ...
38,09/12/19,12:42 pm,AR❤,AR❤: Ok mam thank u
39,10/12/19,7:59 am,Mabel Infoziant,Mabel Infoziant: Ramisha we need to talk toda...
40,10/12/19,8:00 am,Mabel Infoziant,Mabel Infoziant: Be ready to discuss about th...
41,10/12/19,8:55 am,AR❤,AR❤: Okay mam
42,12/12/19,2:26 pm,Mabel Infoziant,Mabel Infoziant: ok
43,15/12/19,8:22 pm,AR❤,AR❤: Mam are u free?
44,15/12/19,8:40 pm,Mabel Infoziant,Mabel Infoziant: Am at church can call very l...
45,15/12/19,8:40 pm,AR❤,AR❤: Kk mam. I will ask Arun brother. Small d...
46,18/12/19,3:09 pm,AR❤,AR❤: Hi mam
47,18/12/19,3:09 pm,AR❤,AR❤: Any updates mam?
48,18/12/19,3:11 pm,Mabel Infoziant,Mabel Infoziant: U might have to start on the...
49,18/12/19,3:11 pm,Mabel Infoziant,Mabel Infoziant: There is one project that go...
50,18/12/19,3:12 pm,AR❤,AR❤: Kk mam👍🏻

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 1 to 50
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    50 non-null     object
 1   Time    50 non-null     object
 2   Name    50 non-null     object
 3   Chat    50 non-null     object
dtypes: object(4)
memory usage: 1.7+ KB

In [56]:
import nltk
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\sheik\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [84]:
# use in-built - library - nltk - natural language tool kit
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [58]:
dataset = df

In [59]:
dataset.dropna(inplace=True)

C:\Users\sheik\AppData\Local\Temp\ipykernel_76980\2639109627.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset.dropna(inplace=True)

In [61]:
sid = SentimentIntensityAnalyzer()

In [63]:
senti = sid.polarity_scores(dataset['Chat'][4])

In [73]:
senti

{'neg': 0.0, 'neu': 0.476, 'pos': 0.524, 'compound': 0.296}

In [83]:
# resuable function sentimentalAnalysis pass data and columnname
def sentimentalAnalysis(data, columnName):
    #downloading vader_lexicon for the process
    import matplotlib.pyplot as plt
    import seaborn as sns
    "Importing Necessary Package"
    from nltk.sentiment.vader import SentimentIntensityAnalyzer
    sid = SentimentIntensityAnalyzer()

    "Deleting null pr empty value"
    data.dropna(inplace=True)

    "Checking for a comment"
    #sid.polarity_score(data[columnName][]93)

    "Creating respective columns"
    data['scores'] = data[columnName].apply(lambda commentText: sid.polarity_scores(commentText))
    data['compound'] = data['scores'].apply(lambda score_dict: score_dict['compound'])
    data['Negative'] = data['scores'].apply(lambda score_dict: score_dict['neg'])
    data['Positive'] = data['scores'].apply(lambda score_dict: score_dict['pos'])
    data['Neutral'] = data['scores'].apply(lambda score_dict: score_dict['neu'])

    "Creating final pos or neg using compound score"
    data['comp_score'] = data['compound'].apply(lambda c: 'pos' if c >=0 else 'neg')
    plt.clf()
    
    #comp=sns.countplot(x = 'comp_score', hue = 'Nmae', data = data, palette = 'magma')
    #comp.figure.savefig("data_charts.png")

    "Checking how many pos and neg"
    posneg = pd.DataFrame(data['comp_score'].value_counts())
    return posneg,data

In [80]:
pos,data_Senti = sentimentalAnalysis(dataset,columnName='Chat')

In [81]:
data_Senti

,Date,Time,Name,Chat,scores,compound,Negtive,Postive,Neutral,comp_score,Negative,Positive
1,05/12/19,1:42 pm,Mabel Infoziant,Mabel Infoziant: Hi this is Mabel we just spoke,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0.000,0.000
2,05/12/19,1:42 pm,Mabel Infoziant,Mabel Infoziant: What’s your full name,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0.000,0.000
3,05/12/19,1:42 pm,AR❤,AR❤: Ramisha Rani K,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0.000,0.000
4,05/12/19,1:42 pm,Mabel Infoziant,Mabel Infoziant: Ok,"{'neg': 0.0, 'neu': 0.476, 'pos': 0.524, 'comp...",0.2960,0.000,0.524,0.476,pos,0.000,0.524
5,05/12/19,1:42 pm,Mabel Infoziant,Mabel Infoziant: ramisharanik@gmail.com,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0.000,0.000
6,05/12/19,1:43 pm,Mabel Infoziant,Mabel Infoziant: Your email Id?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0.000,0.000
7,05/12/19,1:43 pm,AR❤,AR❤: Yes Mam,"{'neg': 0.0, 'neu': 0.426, 'pos': 0.574, 'comp...",0.4019,0.000,0.574,0.426,pos,0.000,0.574
8,05/12/19,1:43 pm,Mabel Infoziant,Mabel Infoziant: I will send 2 abstracts for ...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0.000,0.000
9,05/12/19,1:43 pm,AR❤,AR❤: Yeah mam,"{'neg': 0.0, 'neu': 0.476, 'pos': 0.524, 'comp...",0.2960,0.000,0.524,0.476,pos,0.000,0.524
10,05/12/19,1:43 pm,Mabel Infoziant,Mabel Infoziant: Give me the list that u have...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0.000,0.000
11,05/12/19,1:43 pm,Mabel Infoziant,Mabel Infoziant: Send me cbe office address a...,"{'neg': 0.0, 'neu': 0.925, 'pos': 0.075, 'comp...",0.0772,0.000,0.075,0.925,pos,0.000,0.075
12,05/12/19,1:44 pm,AR❤,AR❤: Yeah Mam within Evening I will forward y...,"{'neg': 0.0, 'neu': 0.784, 'pos': 0.216, 'comp...",0.2960,0.000,0.216,0.784,pos,0.000,0.216
13,05/12/19,1:45 pm,AR❤,AR❤: Tomorrow I have to visit the office.yet ...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0.000,0.000
14,05/12/19,1:48 pm,Mabel Infoziant,Mabel Infoziant: ok,"{'neg': 0.0, 'neu': 0.476, 'pos': 0.524, 'comp...",0.2960,0.000,0.524,0.476,pos,0.000,0.524
15,05/12/19,1:48 pm,Mabel Infoziant,Mabel Infoziant: send the details of office l...,"{'neg': 0.0, 'neu': 0.901, 'pos': 0.099, 'comp...",0.3612,0.000,0.099,0.901,pos,0.000,0.099
16,05/12/19,1:49 pm,AR❤,AR❤: Sure mam. Soon I will share details with...,"{'neg': 0.0, 'neu': 0.64, 'pos': 0.36, 'compou...",0.5423,0.000,0.360,0.640,pos,0.000,0.360
17,05/12/19,2:00 pm,AR❤,AR❤: I have read the Abstract mam. We can do ...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0.000,0.000
18,05/12/19,2:04 pm,Mabel Infoziant,Mabel Infoziant: I think Vignesh has the data...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0.000,0.000
19,05/12/19,2:04 pm,Mabel Infoziant,Mabel Infoziant: I have sent the abstracts,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0.000,0.000
20,05/12/19,2:06 pm,AR❤,AR❤: Ok mam,"{'neg': 0.0, 'neu': 0.476, 'pos': 0.524, 'comp...",0.2960,0.000,0.524,0.476,pos,0.000,0.524
21,05/12/19,2:07 pm,AR❤,AR❤: I have read both the abstract mam. We ca...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0.000,0.000
22,05/12/19,4:44 pm,Mabel Infoziant,Mabel Infoziant: Yes we need to ya about amou...,"{'neg': 0.0, 'neu': 0.856, 'pos': 0.144, 'comp...",0.4019,0.000,0.144,0.856,pos,0.000,0.144
23,05/12/19,4:48 pm,AR❤,AR❤: Sure mam.,"{'neg': 0.0, 'neu': 0.465, 'pos': 0.535, 'comp...",0.3182,0.000,0.535,0.465,pos,0.000,0.535
24,05/12/19,8:07 pm,AR❤,AR❤: Shall I call mam?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0.000,0.000
25,08/12/19,10:45 pm,Mabel Infoziant,Mabel Infoziant: Hi I was at church couldn’t ...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0.000,0.000
26,08/12/19,11:52 pm,AR❤,AR❤: It's k mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0.000,0.000
27,08/12/19,11:55 pm,AR❤,AR❤: Just to know the tomorrow plan mam.will ...,"{'neg': 0.0, 'neu': 0.791, 'pos': 0.209, 'comp...",0.4404,0.000,0.209,0.791,pos,0.000,0.209
28,09/12/19,12:09 pm,AR❤,AR❤: Mam can u send Vignesh number??,"{'neg': 0.0, 'neu': 0.751, 'pos': 0.249, 'comp...",0.1680,0.000,0.249,0.751,pos,0.000,0.249
29,09/12/19,12:13 pm,Mabel Infoziant,Mabel Infoziant: Vignesh ML Infoziant.vcf (fi...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0.000,0.000
30,09/12/19,12:23 pm,Mabel Infoziant,Mabel Infoziant: I was in a meeting sorry,"{'neg': 0.206, 'neu': 0.794, 'pos': 0.0, 'comp...",-0.0772,0.206,0.000,0.794,neg,0.206,0.000
31,09/12/19,12:25 pm,AR❤,AR❤: Can I cal u mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0.000,0.000
32,09/12/19,12:26 pm,AR❤,AR❤: Waiting for u r finalization of rates fo...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0.000,0.000
33,09/12/19,12:26 pm,AR❤,AR❤: If we finiliaze I can work with full inv...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0.000,0.000
34,09/12/19,12:28 pm,AR❤,AR❤: So what ever may be ..if you think your ...,"{'neg': 0.0, 'neu': 0.879, 'pos': 0.121, 'comp...",0.5106,0.000,0.121,0.879,pos,0.000,0.121
35,09/12/19,12:28 pm,AR❤,AR❤: You deleted this message,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0.000,0.000
36,09/12/19,12:29 pm,AR❤,AR❤: Do the needful,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0.000,0.000
37,09/12/19,12:41 pm,Mabel Infoziant,Mabel Infoziant: No ma please hold I am in a ...,"{'neg': 0.162, 'neu': 0.755, 'pos': 0.083, 'co...",-0.2960,0.162,0.083,0.755,neg,0.162,0.083
38,09/12/19,12:42 pm,AR❤,AR❤: Ok mam thank u,"{'neg': 0.0, 'neu': 0.299, 'pos': 0.701, 'comp...",0.5719,0.000,0.701,0.299,pos,0.000,0.701
39,10/12/19,7:59 am,Mabel Infoziant,Mabel Infoziant: Ramisha we need to talk toda...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0.000,0.000
40,10/12/19,8:00 am,Mabel Infoziant,Mabel Infoziant: Be ready to discuss about th...,"{'neg': 0.0, 'neu': 0.8, 'pos': 0.2, 'compound...",0.3612,0.000,0.200,0.800,pos,0.000,0.200
41,10/12/19,8:55 am,AR❤,AR❤: Okay mam,"{'neg': 0.0, 'neu': 0.513, 'pos': 0.487, 'comp...",0.2263,0.000,0.487,0.513,pos,0.000,0.487
42,12/12/19,2:26 pm,Mabel Infoziant,Mabel Infoziant: ok,"{'neg': 0.0, 'neu': 0.476, 'pos': 0.524, 'comp...",0.2960,0.000,0.524,0.476,pos,0.000,0.524
43,15/12/19,8:22 pm,AR❤,AR❤: Mam are u free?,"{'neg': 0.0, 'neu': 0.476, 'pos': 0.524, 'comp...",0.5106,0.000,0.524,0.476,pos,0.000,0.524
44,15/12/19,8:40 pm,Mabel Infoziant,Mabel Infoziant: Am at church can call very l...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0.000,0.000
45,15/12/19,8:40 pm,AR❤,AR❤: Kk mam. I will ask Arun brother. Small d...,"{'neg': 0.106, 'neu': 0.636, 'pos': 0.258, 'co...",0.5574,0.106,0.258,0.636,pos,0.106,0.258
46,18/12/19,3:09 pm,AR❤,AR❤: Hi mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0.000,0.000
47,18/12/19,3:09 pm,AR❤,AR❤: Any updates mam?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0.000,0.000
48,18/12/19,3:11 pm,Mabel Infoziant,Mabel Infoziant: U might have to start on the...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0.000,0.000
49,18/12/19,3:11 pm,Mabel Infoziant,Mabel Infoziant: There is one project that go...,"{'neg': 0.0, 'neu': 0.792, 'pos': 0.208, 'comp...",0.2732,0.000,0.208,0.792,pos,0.000,0.208
50,18/12/19,3:12 pm,AR❤,AR❤: Kk mam👍🏻,"{'neg': 0.0, 'neu': 0.444, 'pos': 0.556, 'comp...",0.3612,0.000,0.556,0.444,pos,0.000,0.556

In [82]:
pos

            count
comp_score
pos            48
neg             2